name: Merge
description: Automatically merge master into PRs
inputs:
  token:
    required: true
    description: "Token to perform api calls"

outputs:
  mergedPrNumbers:
    description: "Multi-line list of PR numbers successfully merged"
  conflictedPrNumbers:
    description: "Multi-line list of PR numbers not merged due to conflicts"

runs:
  using: node12
  main: dist/index.js

branding:
  icon: git-merge
  color: green
